#!/usr/bin/bash
if [ "$1" != "" ]; then class="$1"; else echo "Please enter class name."; read class; fi
cs="$class.cs"
echo "using System;">$cs
echo "">>$cs
echo "namespace ${PWD##*/}">>$cs
echo "{">>$cs
echo -e "\tpublic class $class">>$cs
echo -e "\t{">>$cs
if [ "$class" == "Program" ]; then
	echo -e "\t\tpublic static void Main(string[] args)">>$cs
	echo -e "\t\t{">>$cs
	echo -e "\t\t\t">>$cs
	echo -e "\t\t}">>$cs
else
echo -e "\t\t">>$cs
fi
echo -e "\t}">>$cs
echo "}">>$cs